### ISSUE TITLE
Change Usage Of The PNG In Background To CSS

### ISSUE THREAD

**Issue by sifes** [fictadvisor/fictadvisor#446]
The current implementation of our project uses a PNG image as the background for the main section. To improve performance, reduce loading times, and enhance flexibility, we need to replace the PNG background with a CSS gradient.

### 1. **Background Replacement**
   - **Remove the PNG Background**: Identify the code where the PNG image is applied as the background and remove it.
   - **Apply CSS Gradient**: Replace the PNG with a CSS radial or linear gradient that provides a similar aesthetic to the original image, or improves upon it. Ensure that the gradient is responsive and visually appealing across different screen sizes.

### 2. **Performance Optimization**
   - By switching to a CSS gradient, we eliminate the need for an external image file, reducing the overall page load time and improving performance, especially on slower networks.

### 3. **Responsive Design**
   - Ensure that the gradient adapts well to different screen sizes and devices, maintaining visual quality and aesthetic appeal on mobile, tablet, and desktop views.

## Benefits of CSS Gradient Implementation

- **Improved Performance**: Eliminating the need to load a PNG image reduces the overall page size, resulting in faster load times.
- **Flexibility**: CSS gradients are easily customizable, allowing for future adjustments without needing to create new image files.
- **Consistency**: Gradients scale better across different screen resolutions and sizes, ensuring a consistent design across devices.

## Reference 
```css
.wrapper {
  position: relative;

  &::before,
  &::after {
    content: '';
    position: absolute;
  }

  &::before {
    width: 750px;
    height: 550px;
    background: radial-gradient(rgba(187, 143, 255, 0.9) 25%, rgba(255, 255, 255, 0) 70%);
    right: 150px;
    top: 150px;
    z-index: -1;
    opacity: 0.5;
    @include lg {
      top: unset;
      bottom: -150px;
    }
  }

  &::after {
    width: 550px;
    height: 500px;
    background: radial-gradient(rgba(172, 154, 255, 0.9) 25%, rgba(255, 255, 255, 0) 70%);
    top: 50px;
    right: -50px;
    z-index: -1;
    opacity: 0.75;
  }
}
```
